# Generated by Django 5.2.3 on 2025-07-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_rename_usuario_comentario_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='usuario',
        ),
    ]
