# Generated by Django 5.2.1 on 2025-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subcategoria', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('tipo', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('contenido_texto', models.TextField(default='')),
                ('subcategoria2', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('contenido_texto2', models.TextField(default='')),
                ('subcategoria3', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('gameplay', models.FileField(blank=True, default='resumen', null=True, upload_to='')),
                ('subcategoria4', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('contenido_texto4', models.TextField(default='')),
                ('subcategoria5', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20)),
                ('imagenes', models.ImageField(upload_to='')),
            ],
        ),
    ]
