# Generated by Django 5.2.1 on 2025-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('imagenes', models.ImageField(upload_to='')),
                ('videos', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
