# Generated by Django 5.2.3 on 2025-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='gameplay',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('juego', 'Juego'), ('serie', 'Serie'), ('pelicula', 'Película')], default='juego', max_length=20),
        ),
    ]
