# Generated by Django 5.2.1 on 2025-06-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto',
            field=models.TextField(default=''),
        ),
    ]
