# Generated by Django 5.2.1 on 2025-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_contenido_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='videos',
            new_name='gameplay',
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria2',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria3',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria4',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria5',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
    ]
