# Generated by Django 5.2.3 on 2025-06-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_gameplay_alter_articulo_imagenes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='contenido_texto',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='contenido_texto2',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='contenido_texto4',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='gameplay',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcategoria2',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcategoria3',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcategoria4',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='subcategoria5',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], max_length=20)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='articulos.articulo')),
            ],
        ),
    ]
