# Generated by Django 5.2.3 on 2025-06-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_contenido_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='videos',
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='gameplay',
            field=models.FileField(blank=True, default='resumen', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria2',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria3',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria4',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria5',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
    ]
