# Generated by Django 5.2.3 on 2025-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_articulo_contenido_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='gameplay',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria2',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria3',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria4',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria5',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='resumen', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
