# Generated by Django 5.2.3 on 2025-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_articulo_contenido_texto_articulo_contenido_texto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido_texto4',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
