# Generated by Django 5.2.3 on 2025-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_articulo_contenido_texto4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria2',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='historia', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria3',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='gameplay', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria4',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='guias', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria5',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes')], default='galeria', max_length=20),
        ),
    ]
