# Generated by Django 5.2.3 on 2025-07-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_articulo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
    ]
