# Generated by Django 5.2.3 on 2025-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_remove_articulo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto17',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='contenido_texto9',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_cosplay',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/cosplay/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_fanart',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/fanart/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_memes',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/memes/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_merchandising',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/merchandising/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria10',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='análisis', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria11',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='curiosidades', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria12',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='trivia', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria13',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='fanart', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria14',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='memes', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria15',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='cosplay', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria16',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='merchandising', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria17',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='eventos', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria6',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='noticias', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria7',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='entrevistas', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria8',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='reseñas', max_length=20),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria9',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='opiniones', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='resumen', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria2',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='historia', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria3',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='gameplay', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria4',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='guias', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subcategoria5',
            field=models.CharField(choices=[('resumen', 'Resumen'), ('historia', 'Historia'), ('gameplay', 'Gameplay'), ('guias', 'Guías'), ('galeria', 'Galería de imágenes'), ('noticias', 'Noticias'), ('entrevistas', 'Entrevistas'), ('reseñas', 'Reseñas'), ('opiniones', 'Opiniones'), ('análisis', 'Análisis'), ('curiosidades', 'Curiosidades'), ('trivia', 'Trivia'), ('fanart', 'Fanart'), ('memes', 'Memes'), ('cosplay', 'Cosplay'), ('merchandising', 'Merchandising'), ('eventos', 'Eventos')], default='galeria', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('juego', 'Juego'), ('serie', 'Serie'), ('pelicula', 'Película'), ('anime', 'Anime'), ('libro', 'Libro'), ('musica', 'Música'), ('otro', 'Otro')], default='juego', max_length=20),
        ),
    ]
